-- Tabela de contatos do formulário do site
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  message TEXT,
  service_interest TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de agendamentos (opcional, para controle interno)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name TEXT NOT NULL,
  patient_email TEXT NOT NULL,
  patient_phone TEXT NOT NULL,
  service_id TEXT NOT NULL,
  preferred_date DATE,
  preferred_time TIME,
  status TEXT DEFAULT 'pending', -- pending, confirmed, cancelled, completed
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) se necessário
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- Criar políticas para permitir inserção pública (para o formulário do site)
CREATE POLICY "Allow public insert to contacts" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert to appointments" ON appointments FOR INSERT WITH CHECK (true);

-- Criar políticas para permitir leitura apenas para usuários autenticados (admin)
-- Nota: Isso assume que você configurará usuários no Supabase futuramente
-- CREATE POLICY "Allow authenticated read to contacts" ON contacts FOR SELECT USING (auth.role() = 'authenticated');
-- CREATE POLICY "Allow authenticated read to appointments" ON appointments FOR SELECT USING (auth.role() = 'authenticated');
